version: "3.7"

services:

  build:
    image: cataloteca_front
    container_name: build
    build:
      context: .
    command: yarn
    volumes:
      - .:/app
    networks: 
      - cataloteca

  front:
    image: cataloteca_front
    container_name: front
    build:
      context: .
    command: yarn start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    networks: 
      - cataloteca
    depends_on:
      - build

networks:
  cataloteca:
    external:
      name: cataloteca